services:
  yt-to-gif:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yt-to-gif-bot
    restart: unless-stopped
    environment:
      NODE_ENV: production
    env_file:
      - .env
    volumes:
      # Mount for temporary files if needed
      - /tmp:/tmp:rw
      # Mount SSH key with specific permissions
      - ${HOME}/.ssh/keys/docker_hetzner_rsa:/ssh-keys/docker_hetzner_rsa:ro
    # Uncomment if your bot needs network access restrictions
    # networks:
    #   - bot-network
    # Resource limits for lightweight deployment
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Uncomment if using network isolation
# networks:
#   bot-network:
#     driver: bridge